# Generated by Django 5.0.7 on 2025-08-14 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avatar', models.ImageField(blank=True, help_text='PNG с прозрачностью 512x512, будет поставлен внизу слева/справа.', null=True, upload_to='dialogue/avatars/')),
                ('default_side', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='left', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DialogueScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('use_bg', models.BooleanField(default=False, help_text='Включить фон для сцены')),
                ('background', models.ImageField(blank=True, null=True, upload_to='dialogue/backgrounds/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DialogueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Порядок в сцене (сортировка по возрастанию)')),
                ('character_name', models.CharField(blank=True, default='', help_text='Если пусто — будет использовано имя персонажа из справочника', max_length=100)),
                ('side', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='left', help_text='С какой стороны появится аватар на экране для этой реплики', max_length=5)),
                ('avatar_override', models.ImageField(blank=True, help_text='Опционально: переопределить аватар именно для этой реплики', null=True, upload_to='dialogue/line_avatars/')),
                ('text', models.TextField(help_text='Текст реплики (будет печататься по символам)')),
                ('typing_speed_ms', models.PositiveIntegerField(default=18, help_text='Скорость печати (мс на символ)')),
                ('pause_after_ms', models.PositiveIntegerField(default=400, help_text='Пауза после завершения печати')),
                ('audio', models.FileField(blank=True, help_text='Опционально: аудио, воспроизводится вместе с печатью', null=True, upload_to='dialogue/audio/')),
                ('volume', models.FloatField(default=1.0, help_text='Громкость 0.0—1.0')),
                ('bg_override', models.ImageField(blank=True, help_text='Опционально: фон только на время этой реплики', null=True, upload_to='dialogue/line_backgrounds/')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.character')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='courses.dialoguescene')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
