# Generated by Django 5.0.7 on 2025-08-27 04:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_character_dialoguescene_dialogueline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_course',
            field=models.CharField(blank=True, choices=[('scratch-junior', 'Scratch Junior'), ('scratch', 'Scratch'), ('roblox', 'Roblox'), ('blockbench', 'Blockbench'), ('blender', 'Blender'), ('unity', 'Unity'), ('python-basic', 'Python basic'), ('pygame', 'Pygame'), ('telegram-bots', 'Telegram bots'), ('olympiad-python', 'Olympiad python'), ('web-dev', 'Web dev'), ('computer-literacy', 'Computer literacy'), ('block-python', 'Block python'), ('figma-tilda', 'Figma Tilda')], max_length=50, verbose_name='Текущий курс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lessons_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс уроков'),
        ),
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent_goal',
            field=models.TextField(blank=True, verbose_name='Цели обучения (комментарий родителя)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trial_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий пробного занятия'),
        ),
        migrations.CreateModel(
            name='LessonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема урока')),
                ('homework', models.TextField(blank=True, verbose_name='Домашнее задание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий учителя')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_stats', to='courses.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tg', 'Telegram'), ('wa', 'WhatsApp'), ('vk', 'ВКонтакте'), ('mx', 'MAX')], max_length=10)),
                ('login', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messengers', to='courses.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, verbose_name='Телефон')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='courses.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Пн'), (1, 'Вт'), (2, 'Ср'), (3, 'Чт'), (4, 'Пт'), (5, 'Сб'), (6, 'Вс')], verbose_name='День недели')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='courses.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StudyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100, verbose_name='Платформа')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_accounts', to='courses.profile')),
            ],
        ),
    ]
