# Generated by Django 5.0.7 on 2025-08-27 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_profile_birth_date_profile_current_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя для отображения')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('api_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('students', models.ManyToManyField(blank=True, related_name='teachers', to='courses.profile')),
            ],
        ),
    ]
