# Generated by Django 5.0.7 on 2025-08-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='duration_min',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)'),
        ),
    ]
