# Generated by Django 5.0.7 on 2025-08-27 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_scheduleentry_duration_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to='courses.teacher', verbose_name='Учитель'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zoom_link',
            field=models.URLField(blank=True, default='', verbose_name='Zoom-ссылка'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ID конференции'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zoom_passcode',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Пароль конференции'),
        ),
    ]
