# Generated by Django 5.0.7 on 2025-08-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_scheduleentry_teacher_teacher_zoom_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo_url',
            field=models.URLField(blank=True, default='', verbose_name='Фото (URL)'),
        ),
    ]
