# Generated by Django 5.0.7 on 2025-08-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_teacher_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='Фото'),
        ),
    ]
